/**
 * The drawings committed under public/art.
 *
 * The sandbox holds no photographs, so every seeded thing points at a drawing
 * instead: a flat scene in the lokal palette, generated by
 * scripts/generate-demo-art.mjs. Rows refer to one by key, never by path, so
 * the art can move or be served from a CDN later without a data migration.
 *
 * A key is a file name without the extension, like `cafe-coffee` or
 * `logo-cup`. Anything that already looks like a URL or a path is passed
 * through untouched, because a real upload has replaced the drawing and there
 * is nothing to resolve.
 */

/** Where the drawings are served from. They are static files, not uploads. */
const ART_BASE = '/art';

/** Keys are file names, so anything else is a mistake worth catching early. */
const KEY_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/**
 * Turn a bundled art key into something an <img src> can use.
 *
 * Returns null for a missing or malformed key so the caller falls back to the
 * kind tile rather than requesting a URL that will 404.
 */
export function artUrl(key: string | null | undefined): string | null {
  if (!key) return null;
  if (key.startsWith('/') || key.startsWith('http') || key.startsWith('data:')) return key;
  if (!KEY_PATTERN.test(key)) return null;
  return `${ART_BASE}/${key}.svg`;
}

/** True when a URL points at the bundled art rather than at a real photograph. */
export function isBundledArt(url: string | null | undefined): boolean {
  return !!url && url.startsWith(`${ART_BASE}/`);
}
