import {
  Activity,
  AlertTriangle,
  Baby,
  BadgeCheck,
  BookOpen,
  Briefcase,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarHeart,
  Car,
  ChevronRight,
  Circle,
  Clock,
  Coffee,
  Crown,
  Flame,
  Gift,
  GraduationCap,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  Home,
  MapPin,
  Mountain,
  Music,
  PackagePlus,
  Palette,
  PartyPopper,
  PiggyBank,
  Presentation,
  Radio,
  School,
  Search,
  ShoppingBag,
  Sparkle,
  Sparkles,
  Sprout,
  Store,
  Tag,
  ThumbsUp,
  Trash2,
  Star,
  Users,
  UtensilsCrossed,
  Wine,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  Activity,
  AlertTriangle,
  Baby,
  BadgeCheck,
  BookOpen,
  Briefcase,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarHeart,
  Car,
  ChevronRight,
  Circle,
  Clock,
  Coffee,
  Crown,
  Flame,
  Gift,
  GraduationCap,
  HandHeart,
  Heart,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  Home,
  MapPin,
  Mountain,
  Music,
  PackagePlus,
  Palette,
  PartyPopper,
  PiggyBank,
  Presentation,
  Radio,
  School,
  Search,
  ShoppingBag,
  Sparkle,
  Sparkles,
  Sprout,
  Store,
  Tag,
  ThumbsUp,
  Trash2,
  Star,
  UserStar: Star,
  Users,
  UtensilsCrossed,
  Wine,
  Wrench,
  X,
  Zap,
};

export function resolveIcon(name: string | null | undefined, fallback: LucideIcon = Building2): LucideIcon {
  if (!name) return fallback;
  if (ICON_MAP[name]) return ICON_MAP[name];
  const pascal = name.charAt(0).toUpperCase() + name.slice(1).replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
  return ICON_MAP[pascal] || fallback;
}
