project_id = "ixupthihhfeikeydvvir"

[functions.get-signed-urls-batch]
verify_jwt = false

[functions.moderate-content]
verify_jwt = false

[functions.ask-toledo]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.get-signed-url]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.loop-scan-qr]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.process-image]
verify_jwt = false
