import { Badge } from '@/components/ui/badge';
import { Building2, User, Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';

interface AuthorBadgeProps {
  authorType: 'user' | 'business' | 'admin';
  autoGenerated?: boolean;
  className?: string;
}

export function AuthorBadge({ authorType, autoGenerated, className }: AuthorBadgeProps) {
  if (authorType === 'business') {
    return (
      <Badge 
        variant="secondary" 
        className={cn("text-xs gap-1 bg-primary/10 text-primary border-primary/20", className)}
      >
        <Building2 className="h-3 w-3" />
        Business
      </Badge>
    );
  }

  if (autoGenerated) {
    return (
      <Badge 
        variant="secondary" 
        className={cn("text-xs gap-1 bg-secondary text-muted-foreground", className)}
      >
        <Sparkles className="h-3 w-3" />
        Activity
      </Badge>
    );
  }

  return (
    <Badge 
      variant="outline" 
      className={cn("text-xs gap-1 border-muted-foreground/30", className)}
    >
      <User className="h-3 w-3" />
      Resident
    </Badge>
  );
}
