import { useState, useEffect } from 'react';
import { PulsePost, useHidePulsePost } from '@/hooks/usePulse';
import {
  formatTimeRemaining,
  PULSE_CONTENT_TYPES,
  getTemplate,
  PULSE_CATEGORY_TAGS,
} from '@/lib/pulse-config';
import { useAuth } from '@/contexts/AuthContext';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { SecureAvatar } from '@/components/ui/secure-avatar';
import { SecureImage } from '@/components/ui/secure-image';
import { PulseShareButton } from './PulseShareButton';
import { AuthorBadge } from './AuthorBadge';
import { ReactionBar } from './ReactionBar';
import { PulseReportDialog } from './PulseReportDialog';
import { PulseIcon } from './PulseIcon';
import { CalendarDays, Clock, MapPin, MoreVertical, Pin, Trash2, Flag } from 'lucide-react';
import { Link } from 'react-router-dom';
import { cn } from '@/lib/utils';
import { useToast } from '@/hooks/use-toast';

interface PulsePostCardProps {
  post: PulsePost;
}

export function PulsePostCard({ post }: PulsePostCardProps) {
  const { user } = useAuth();
  const { toast } = useToast();
  const hidePost = useHidePulsePost();
  const [timeRemaining, setTimeRemaining] = useState(formatTimeRemaining(new Date(post.expires_at)));
  const [reportOpen, setReportOpen] = useState(false);

  const typeConfig = PULSE_CONTENT_TYPES[post.content_type] ?? PULSE_CONTENT_TYPES.business_activity;
  const template = getTemplate(post.template_key);
  const isOwner = (post.user_id && post.user_id === user?.id) || !!(post.business_id && post.business?.id);

  useEffect(() => {
    const interval = setInterval(() => {
      setTimeRemaining(formatTimeRemaining(new Date(post.expires_at)));
    }, 60000);
    return () => clearInterval(interval);
  }, [post.expires_at]);

  const handleHide = async () => {
    try {
      await hidePost.mutateAsync(post.id);
      toast({ title: 'Post removed' });
    } catch {
      toast({ variant: 'destructive', title: 'Error removing post' });
    }
  };

  const authorName = post.business?.name || post.nonprofit?.name || post.author?.name || 'Toledo Local';
  const authorInitial = authorName.charAt(0).toUpperCase();
  const categoryTags = PULSE_CATEGORY_TAGS.filter((c) => post.tags?.includes(c.id));

  return (
    <article
      className={cn(
        'relative overflow-hidden rounded-2xl border bg-card transition-all',
        post.is_pinned ? 'border-primary/30' : 'border-border/50 hover:border-border'
      )}
    >
      {post.is_pinned && (
        <div className="absolute right-3 top-3 z-10">
          <Badge className="gap-1 bg-primary text-primary-foreground text-[10px]">
            <Pin className="h-2.5 w-2.5" />
            Pinned
          </Badge>
        </div>
      )}

      {/* Image-first hero */}
      {post.hero_image && (
        <Link to={`/pulse/${post.pulse_id || post.id}`} className="block">
          <SecureImage
            storagePath={post.hero_image}
            alt={post.headline || post.content}
            className="h-44 w-full"
            imgClassName="object-cover"
          />
        </Link>
      )}

      <div className="p-4">
        {/* Header row */}
        <div className="flex items-start gap-2.5">
          {post.business ? (
            <Link to={`/business/${post.business.id}`}>
              <SecureAvatar storagePath={post.business.logo_url} fallbackText={post.business.name} className="h-9 w-9" />
            </Link>
          ) : (
            <SecureAvatar
              storagePath={post.author?.avatar_url}
              fallbackText={authorName}
              className="h-9 w-9"
              fallbackClassName="bg-secondary text-foreground text-sm"
            />
          )}

          <div className="min-w-0 flex-1">
            <div className="flex flex-wrap items-center gap-1.5">
              <span className="truncate text-sm font-semibold text-foreground">
                {post.anonymous ? 'Toledo Local' : authorName}
              </span>
              <AuthorBadge authorType={post.author_type} autoGenerated={post.auto_generated} />
            </div>
            <div className="mt-0.5 flex flex-wrap items-center gap-x-2 gap-y-0.5 text-xs text-muted-foreground">
              <span className={cn('inline-flex items-center gap-1 font-medium', typeConfig.accent)}>
                <PulseIcon name={template?.icon || typeConfig.icon} className="h-3 w-3" />
                {template?.label || typeConfig.label}
              </span>
              {post.neighborhood && (
                <span className="inline-flex items-center gap-0.5">
                  <MapPin className="h-3 w-3" />
                  {post.neighborhood}
                </span>
              )}
              <span className="inline-flex items-center gap-0.5">
                <Clock className="h-3 w-3" />
                {timeRemaining}
              </span>
            </div>
          </div>

          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="ghost" size="icon" className="h-7 w-7 shrink-0">
                <MoreVertical className="h-4 w-4" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="bg-popover border border-border">
              <DropdownMenuItem onClick={() => setReportOpen(true)}>
                <Flag className="mr-2 h-4 w-4" />
                Report post
              </DropdownMenuItem>
              {isOwner && (
                <DropdownMenuItem onClick={handleHide} className="text-destructive focus:text-destructive">
                  <Trash2 className="mr-2 h-4 w-4" />
                  Remove post
                </DropdownMenuItem>
              )}
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        {/* Body */}
        <Link to={`/pulse/${post.pulse_id || post.id}`} className="mt-2.5 block">
          {post.headline && (
            <h3 className="text-base font-semibold leading-snug text-foreground">{post.headline}</h3>
          )}
          <p
            className={cn(
              'leading-snug text-foreground transition-colors hover:text-primary',
              post.content_type === 'local_moment'
                ? 'text-[1.15rem]'
                : 'text-[0.95rem]'
            )}
            style={
              post.content_type === 'local_moment'
                ? { fontFamily: "'Instrument Serif', Georgia, serif", lineHeight: 1.35 }
                : undefined
            }
          >
            {post.content}
          </p>
        </Link>

        {/* Event details */}
        {post.post_type === 'event' && post.event_date && (
          <div className="mt-2 flex flex-wrap items-center gap-x-3 gap-y-1 rounded-lg bg-secondary/50 px-3 py-2 text-xs font-medium text-foreground">
            <span className="inline-flex items-center gap-1">
              <CalendarDays className="h-3 w-3 text-primary" />
              {new Date(post.event_date + 'T00:00:00').toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' })}
            </span>
            {post.event_start_time && (
              <span className="inline-flex items-center gap-1">
                <Clock className="h-3 w-3 text-primary" />
                {post.event_start_time.slice(0, 5)}
                {post.event_end_time ? ` – ${post.event_end_time.slice(0, 5)}` : ''}
              </span>
            )}
            {post.location_name && (
              <span className="inline-flex items-center gap-1">
                <MapPin className="h-3 w-3 text-primary" />
                {post.location_name}
              </span>
            )}
          </div>
        )}

        {/* Why it matters */}
        {post.why_it_matters && (
          <p className="mt-1.5 text-xs text-muted-foreground">{post.why_it_matters}</p>
        )}

        {/* Tags */}
        {categoryTags.length > 0 && (
          <div className="mt-2 flex flex-wrap gap-1">
            {categoryTags.map((c) => (
              <span key={c.id} className="rounded-full bg-secondary px-2 py-0.5 text-[10px] font-medium text-muted-foreground">
                {c.label}
              </span>
            ))}
          </div>
        )}

        {/* Footer: reactions + share */}
        <div className="mt-3 flex items-center justify-between gap-2 border-t border-border/50 pt-3">
          <ReactionBar post={post} />
          <PulseShareButton post={post} />
        </div>
      </div>

      <PulseReportDialog postId={post.id} open={reportOpen} onOpenChange={setReportOpen} />
    </article>
  );
}
